@startuml

!theme sunlust
left to right direction
skinparam dpi 300
skinparam backgroundColor transparent
skinparam actorStyle awesome
skinparam shadowing false

skinparam package {
    backgroundColor #FFFFFF
    borderColor #555555
}
skinparam usecase {
  backgroundColor #E6F3FF
  borderColor #3995D7
}

' =======================================
' Attori
' =======================================
actor Admin

' =======================================
' Packages e Casi d'Uso
' =======================================

package "Administration" {
  usecase "Manage users" as UC_AdminManageUsers
  usecase "Manage contests" as UC_AdminManageContests
}

' =======================================
' Connessioni
' =======================================

Admin --> UC_AdminManageUsers
Admin --> UC_AdminManageContests

@enduml