@startuml

!theme sunlust
skinparam dpi 300
left to right direction
skinparam backgroundColor transparent
skinparam actorStyle awesome
skinparam shadowing false
skinparam nodesep 25

skinparam package {
    backgroundColor #FFFFFF
    borderColor #555555
}
skinparam usecase {
  backgroundColor #E6F3FF
  borderColor #3995D7
}

' =======================================
' Attori
' =======================================
actor Autenticato
actor Partecipante
actor Organizzatore
actor Giurato

Autenticato <|-- Organizzatore
Autenticato <|-- Giurato
Autenticato <|-- Partecipante

' =======================================
' Packages e Casi d'Uso
' =======================================

package "Gestione Contest" {
  usecase "Crea contest" as UC_CreateContest
  usecase "Modifica contest" as UC_EditContest
  usecase "Elimina contest" as UC_DeleteContest
}

package "Gestione Membri" {
  usecase "Partecipa a contest" as UC_JoinContest
  usecase "Abbandona contest" as UC_LeaveContest

  usecase "Invita partecipante" as UC_InviteParticipant
  usecase "Rimuovi partecipante" as UC_RemoveParticipant

  usecase "Crea giuria" as UC_CreateJury
  usecase "Modifica giuria" as UC_EditJury
  usecase "Elimina giuria" as UC_DeleteJury
  usecase "Invita giurato nominato" as UC_InviteAppointedJuror
  usecase "Rimuovi giurato nominato" as UC_RemoveAppointedJuror

  usecase "Elimina invito" as UC_DeleteInvitation
}

package "Gestione Lavori" {
  usecase "Sottometti lavoro" as UC_SubmitWork
  usecase "Scarica lavoro" as UC_DownloadWork
}

' =======================================
' Connessioni
' =======================================

' Autenticato
Autenticato --> UC_JoinContest
Autenticato --> UC_LeaveContest

' Organizzatore
Organizzatore --> UC_CreateContest
Organizzatore --> UC_EditContest
Organizzatore --> UC_DeleteContest
Organizzatore --> UC_InviteParticipant
Organizzatore --> UC_RemoveParticipant
Organizzatore --> UC_DeleteInvitation
Organizzatore --> UC_CreateJury
Organizzatore --> UC_EditJury
Organizzatore --> UC_DeleteJury
Organizzatore --> UC_InviteAppointedJuror
Organizzatore --> UC_RemoveAppointedJuror
Organizzatore --> UC_DownloadWork

' Partecipante
Partecipante --> UC_SubmitWork
Partecipante --> UC_DownloadWork : {solo il proprio lavoro}

@enduml