@startuml

!theme sunlust
skinparam dpi 300
left to right direction
skinparam backgroundColor transparent
skinparam actorStyle awesome
skinparam shadowing false
skinparam nodesep 25

skinparam package {
    backgroundColor #FFFFFF
    borderColor #555555
}
skinparam usecase {
  backgroundColor #E6F3FF
  borderColor #3995D7
}

' =======================================
' Attori
' =======================================
actor Ospite
actor Autenticato
actor Organizzatore
actor Partecipante
actor Giurato

Autenticato <|-- Organizzatore
Autenticato <|-- Partecipante
Autenticato <|-- Giurato

' =======================================
' Packages e Casi d'Uso
' =======================================

package "Gestione Generale" {
  usecase "Scarica applicazione" as UC_DownloadApplication
}

package "Autenticazione e Gestione Account" {
  usecase "Registrati" as UC_SignUp
  usecase "Accedi" as UC_SignIn
  usecase "Disconnetti" as UC_SignOut
  usecase "Modifica profilo" as UC_EditProfile
  usecase "Elimina account" as UC_DeleteAccount
  usecase "Gestisci notifiche" as UC_ManageNotifications
}

' =======================================
' Connessioni
' =======================================

' Ospite
Ospite --> UC_SignUp
Ospite --> UC_SignIn
Ospite --> UC_DownloadApplication

' Autenticato
Autenticato --> UC_SignOut
Autenticato --> UC_EditProfile
Autenticato --> UC_DeleteAccount
Autenticato --> UC_ManageNotifications

@enduml