import 'package:equatable/equatable.dart';
import 'package:swift_contest/model/database/entities/voting_form.dart';
import 'package:swift_contest/model/database/entities/voting_form_field.dart';
import 'package:swift_contest/model/database/types/voting_form_field_scope.dart';

class VotingFormBundle extends Equatable {
  final VotingForm votingForm;
  final List<VotingFormField> votingFormFields;
  // Autogenerated
  final List<VotingFormField> headerVotingFormFields;
  final List<VotingFormField> participantVotingFormFields;
  final List<VotingFormField> footerVotingFormFields;

   VotingFormBundle({
    required this.votingForm,
    required this.votingFormFields,
  }) : headerVotingFormFields = votingFormFields.where((e) => e.scope.isHeader).toList(growable: false),
       participantVotingFormFields = votingFormFields.where((e) => e.scope.isParticipant).toList(growable: false),
       footerVotingFormFields = votingFormFields.where((e) => e.scope.isFooter).toList(growable: false);

  factory VotingFormBundle.fromJson(Map<String, dynamic> json) {
    return VotingFormBundle(
      votingForm: VotingForm.fromJson(json['voting_form']),
      votingFormFields: (json['voting_form_fields'] as List<dynamic>)
          .map((e) => VotingFormField.fromJson(e))
          .toList(growable: false),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'voting_form': votingForm.toJson(),
      'voting_form_fields': votingFormFields.map((e) => e.toJson()).toList(growable: false),
    };
  }

  VotingFormBundle copyWith({
    VotingForm? votingForm,
    List<VotingFormField>? votingFormFields,
  }) {
    return VotingFormBundle(
      votingForm: votingForm ?? this.votingForm,
      votingFormFields: votingFormFields ?? this.votingFormFields,
    );
  }

  @override
  List<Object?> get props => [votingForm, votingFormFields];
}
