INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, invited_at, confirmation_token, confirmation_sent_at, recovery_token, recovery_sent_at, email_change_token_new, email_change, email_change_sent_at, last_sign_in_at, raw_app_meta_data, raw_user_meta_data, is_super_admin, created_at, updated_at, phone, phone_confirmed_at, phone_change, phone_change_token, phone_change_sent_at, email_change_token_current, email_change_confirm_status, banned_until, reauthentication_token, reauthentication_sent_at, is_sso_user, deleted_at, is_anonymous)
VALUES
	('00000000-0000-0000-0000-000000000000', uuid_generate_v4(), 'authenticated', 'authenticated', 'organizer1@example.com', crypt ('123', gen_salt ('bf')), now(), NULL, '', NULL, '', NULL, '', '', NULL, NULL, '{"provider": "email", "providers": ["email"]}', '{"email_verified": true}', NULL, now(), now(), NULL, NULL, '', '', NULL, '', 0, NULL, '', NULL, false, NULL, false),
	('00000000-0000-0000-0000-000000000000', uuid_generate_v4(), 'authenticated', 'authenticated', 'participant1@example.com', crypt ('123', gen_salt ('bf')), now(), NULL, '', NULL, '', NULL, '', '', NULL, NULL, '{"provider": "email", "providers": ["email"]}', '{"email_verified": true}', NULL, now(), now(), NULL, NULL, '', '', NULL, '', 0, NULL, '', NULL, false, NULL, false),
	('00000000-0000-0000-0000-000000000000', uuid_generate_v4(), 'authenticated', 'authenticated', 'participant2@example.com', crypt ('123', gen_salt ('bf')), now(), NULL, '', NULL, '', NULL, '', '', NULL, NULL, '{"provider": "email", "providers": ["email"]}', '{"email_verified": true}', NULL, now(), now(), NULL, NULL, '', '', NULL, '', 0, NULL, '', NULL, false, NULL, false),
	('00000000-0000-0000-0000-000000000000', uuid_generate_v4(), 'authenticated', 'authenticated', 'participant3@example.com', crypt ('123', gen_salt ('bf')), now(), NULL, '', NULL, '', NULL, '', '', NULL, NULL, '{"provider": "email", "providers": ["email"]}', '{"email_verified": true}', NULL, now(), now(), NULL, NULL, '', '', NULL, '', 0, NULL, '', NULL, false, NULL, false),
	('00000000-0000-0000-0000-000000000000', uuid_generate_v4(), 'authenticated', 'authenticated', 'participant4@example.com', crypt ('123', gen_salt ('bf')), now(), NULL, '', NULL, '', NULL, '', '', NULL, NULL, '{"provider": "email", "providers": ["email"]}', '{"email_verified": true}', NULL, now(), now(), NULL, NULL, '', '', NULL, '', 0, NULL, '', NULL, false, NULL, false),
	('00000000-0000-0000-0000-000000000000', uuid_generate_v4(), 'authenticated', 'authenticated', 'juror1@example.com', crypt ('123', gen_salt ('bf')), now(), NULL, '', NULL, '', NULL, '', '', NULL, NULL, '{"provider": "email", "providers": ["email"]}', '{"email_verified": true}', NULL, now(), now(), NULL, NULL, '', '', NULL, '', 0, NULL, '', NULL, false, NULL, false),
	('00000000-0000-0000-0000-000000000000', uuid_generate_v4(), 'authenticated', 'authenticated', 'juror2@example.com', crypt ('123', gen_salt ('bf')), now(), NULL, '', NULL, '', NULL, '', '', NULL, NULL, '{"provider": "email", "providers": ["email"]}', '{"email_verified": true}', NULL, now(), now(), NULL, NULL, '', '', NULL, '', 0, NULL, '', NULL, false, NULL, false),
	('00000000-0000-0000-0000-000000000000', uuid_generate_v4(), 'authenticated', 'authenticated', 'juror3@example.com', crypt ('123', gen_salt ('bf')), now(), NULL, '', NULL, '', NULL, '', '', NULL, NULL, '{"provider": "email", "providers": ["email"]}', '{"email_verified": true}', NULL, now(), now(), NULL, NULL, '', '', NULL, '', 0, NULL, '', NULL, false, NULL, false),
	('00000000-0000-0000-0000-000000000000', uuid_generate_v4(), 'authenticated', 'authenticated', 'juror4@example.com', crypt ('123', gen_salt ('bf')), now(), NULL, '', NULL, '', NULL, '', '', NULL, NULL, '{"provider": "email", "providers": ["email"]}', '{"email_verified": true}', NULL, now(), now(), NULL, NULL, '', '', NULL, '', 0, NULL, '', NULL, false, NULL, false),
	('00000000-0000-0000-0000-000000000000', uuid_generate_v4(), 'authenticated', 'authenticated', 'user1@example.com', crypt ('123', gen_salt ('bf')), now(), NULL, '', NULL, '', NULL, '', '', NULL, NULL, '{"provider": "email", "providers": ["email"]}', '{"email_verified": true}', NULL, now(), now(), NULL, NULL, '', '', NULL, '', 0, NULL, '', NULL, false, NULL, false),
	('00000000-0000-0000-0000-000000000000', uuid_generate_v4(), 'authenticated', 'authenticated', 'user2@example.com', crypt ('123', gen_salt ('bf')), now(), NULL, '', NULL, '', NULL, '', '', NULL, NULL, '{"provider": "email", "providers": ["email"]}', '{"email_verified": true}', NULL, now(), now(), NULL, NULL, '', '', NULL, '', 0, NULL, '', NULL, false, NULL, false),
	('00000000-0000-0000-0000-000000000000', uuid_generate_v4(), 'authenticated', 'authenticated', 'user3@example.com', crypt ('123', gen_salt ('bf')), now(), NULL, '', NULL, '', NULL, '', '', NULL, NULL, '{"provider": "email", "providers": ["email"]}', '{"email_verified": true}', NULL, now(), now(), NULL, NULL, '', '', NULL, '', 0, NULL, '', NULL, false, NULL, false);

INSERT INTO auth.identities (provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at, id)
VALUES
	(uuid_generate_v4(), (SELECT id FROM auth.users WHERE email = 'organizer1@example.com'), '{"sub": "6495de5f-5e91-43af-9fa9-dbc219afae03", "email": "organizer1@example.com", "email_verified": false, "phone_verified": false}', 'email', now(), now(), now(), uuid_generate_v4()),
	(uuid_generate_v4(), (SELECT id FROM auth.users WHERE email = 'participant1@example.com'), '{"sub": "dc766310-ad6c-400f-9543-c0cb1e3c73fb", "email": "participant1@example.com", "email_verified": false, "phone_verified": false}', 'email', now(), now(), now(), uuid_generate_v4()),
	(uuid_generate_v4(), (SELECT id FROM auth.users WHERE email = 'participant2@example.com'), '{"sub": "2f91cb73-246d-4e66-a034-3c2824dd5d90", "email": "participant2@example.com", "email_verified": false, "phone_verified": false}', 'email', now(), now(), now(), uuid_generate_v4()),
	(uuid_generate_v4(), (SELECT id FROM auth.users WHERE email = 'participant3@example.com'), '{"sub": "ba7585d6-d08a-4dba-9657-5b7987d5b7ed", "email": "participant3@example.com", "email_verified": false, "phone_verified": false}', 'email', now(), now(), now(), uuid_generate_v4()),
	(uuid_generate_v4(), (SELECT id FROM auth.users WHERE email = 'participant4@example.com'), '{"sub": "1dbd3711-9f38-46dc-99b2-751a8e122ae2", "email": "participant4@example.com", "email_verified": false, "phone_verified": false}', 'email', now(), now(), now(), uuid_generate_v4()),
	(uuid_generate_v4(), (SELECT id FROM auth.users WHERE email = 'juror1@example.com'), '{"sub": "ee76f595-cc95-45df-805c-f40fa0be4ef8", "email": "juror1@example.com", "email_verified": false, "phone_verified": false}', 'email', now(), now(), now(), uuid_generate_v4()),
	(uuid_generate_v4(), (SELECT id FROM auth.users WHERE email = 'juror2@example.com'), '{"sub": "fb73dc9e-9166-4bc0-9b6c-5980aa4edb9c", "email": "juror2@example.com", "email_verified": false, "phone_verified": false}', 'email', now(), now(), now(), uuid_generate_v4()),
	(uuid_generate_v4(), (SELECT id FROM auth.users WHERE email = 'juror3@example.com'), '{"sub": "8eb8a4ac-0420-44d8-9172-9efbf951ffd9", "email": "juror3@example.com", "email_verified": false, "phone_verified": false}', 'email', now(), now(), now(), uuid_generate_v4()),
	(uuid_generate_v4(), (SELECT id FROM auth.users WHERE email = 'juror4@example.com'), '{"sub": "bdab3617-6873-4ae3-bfeb-72d4d68caa1d", "email": "juror4@example.com", "email_verified": false, "phone_verified": false}', 'email', now(), now(), now(), uuid_generate_v4()),
	(uuid_generate_v4(), (SELECT id FROM auth.users WHERE email = 'user1@example.com'), '{"sub": "b159bd16-1408-471d-89a7-7bfbed710c32", "email": "user1@example.com", "email_verified": false, "phone_verified": false}', 'email', now(), now(), now(), uuid_generate_v4()),
	(uuid_generate_v4(), (SELECT id FROM auth.users WHERE email = 'user2@example.com'), '{"sub": "b06ff666-9735-4b1c-ba37-2481aac8d3e7", "email": "user2@example.com", "email_verified": false, "phone_verified": false}', 'email', now(), now(), now(), uuid_generate_v4()),
	(uuid_generate_v4(), (SELECT id FROM auth.users WHERE email = 'user3@example.com'), '{"sub": "652e6a20-1122-4d0f-a8f6-696b018e972b", "email": "user3@example.com", "email_verified": false, "phone_verified": false}', 'email', now(), now(), now(), uuid_generate_v4());

-- PROFILES
INSERT INTO profiles (id,created_at,user_id,full_name,pref_role)
VALUES
  (uuid_generate_v4(),now(),(SELECT id FROM auth.users WHERE email = 'organizer1@example.com'),'Organizer1','organizer'),
  (uuid_generate_v4(),now(),(SELECT id FROM auth.users WHERE email = 'participant1@example.com'),'Participant1','participant'),
  (uuid_generate_v4(),now(),(SELECT id FROM auth.users WHERE email = 'participant2@example.com'),'Participant2','participant'),
  (uuid_generate_v4(),now(),(SELECT id FROM auth.users WHERE email = 'participant3@example.com'),'Participant3','participant'),
  (uuid_generate_v4(),now(),(SELECT id FROM auth.users WHERE email = 'participant4@example.com'),'Participant4','participant'),
  (uuid_generate_v4(),now(),(SELECT id FROM auth.users WHERE email = 'juror1@example.com'),'Juror1','juror'),
  (uuid_generate_v4(),now(),(SELECT id FROM auth.users WHERE email = 'juror2@example.com'),'Juror2','juror'),
  (uuid_generate_v4(),now(),(SELECT id FROM auth.users WHERE email = 'juror3@example.com'),'Juror3','juror'),
  (uuid_generate_v4(),now(),(SELECT id FROM auth.users WHERE email = 'juror4@example.com'),'Juror4','juror'),
  (uuid_generate_v4(),now(),(SELECT id FROM auth.users WHERE email = 'user1@example.com'),'User1','organizer'),
  (uuid_generate_v4(),now(),(SELECT id FROM auth.users WHERE email = 'user2@example.com'),'User2','organizer'),
  (uuid_generate_v4(),now(),(SELECT id FROM auth.users WHERE email = 'user3@example.com'),'User3','organizer');

-- todo: Remove
ALTER TABLE auth.users
ENABLE TRIGGER user_created_trigger;

