import 'package:equatable/equatable.dart';
import 'package:swift_contest/model/bundles/juration_bundle.dart';
import 'package:swift_contest/model/bundles/participation_bundle.dart';
import 'package:swift_contest/model/bundles/voting_form_bundle.dart';
import 'package:swift_contest/model/data_models/contest.dart';
import 'package:swift_contest/model/data_models/invitation.dart';
import 'package:swift_contest/model/data_models/juration.dart';
import 'package:swift_contest/model/data_models/participation.dart';
import 'package:swift_contest/model/data_models/place.dart';
import 'package:swift_contest/model/data_models/profile.dart';
import 'package:swift_contest/model/data_models/voting_form.dart';
import 'package:swift_contest/model/data_models/voting_form_field.dart';
import 'package:swift_contest/model/data_models/voting_session.dart';
import 'package:swift_contest/model/data_models/work.dart';
import 'package:swift_contest/model/enums/juror_status.dart';
import 'package:swift_contest/model/enums/member_role.dart';
import 'package:swift_contest/model/enums/participant_status.dart';
import 'package:swift_contest/model/enums/voting_session_status.dart';

class ContestDetailsBundle extends Equatable {
  final Contest contest;
  final Organizer organizer;
  final Place place;
  final List<ParticipationBundle> participationsBundles;
  final List<JurationBundle> jurationsBundles;
  final List<Invitation> invitations;
  final VotingFormBundle votingFormBundle;
  final List<VotingSession> votingSessions;

  // Autogenerated
  final List<ParticipationBundle> joinedParticipationsBundles;
  final List<ParticipationBundle> joinedParticipationsWithWorksBundles;
  final List<ParticipationBundle> joinedParticipationsWithoutWorksBundles;
  final List<ParticipationBundle> outParticipationsBundles;
  final List<Invitation> participantsInvitations;
  final List<JurationBundle> joinedJurationsBundles;
  final List<JurationBundle> outJurationsBundles;
  final List<Invitation> jurorsInvitations;
  final List<VotingSession> endedVotingSessions;
  final VotingSession? liveVotingSession;

  ContestDetailsBundle({
    required this.contest,
    required this.organizer,
    required this.place,
    required this.participationsBundles,
    required this.jurationsBundles,
    required this.invitations,
    required this.votingFormBundle,
    required this.votingSessions,
  })  : joinedParticipationsBundles = participationsBundles
            .where((e) => e.participation.participantStatus.isJoined)
            .toList(growable: false),
        joinedParticipationsWithWorksBundles = participationsBundles
            .where(
                (e) => e.participation.participantStatus.isJoined && e.participation.hasSubmitted)
            .toList(growable: false),
        joinedParticipationsWithoutWorksBundles = participationsBundles
            .where(
                (e) => e.participation.participantStatus.isJoined && !e.participation.hasSubmitted)
            .toList(growable: false),
        outParticipationsBundles = participationsBundles
            .where((e) => e.participation.participantStatus.isOut)
            .toList(growable: false),
        joinedJurationsBundles =
            jurationsBundles.where((e) => e.juration.jurorStatus.isJoined).toList(growable: false),
        outJurationsBundles =
            jurationsBundles.where((e) => e.juration.jurorStatus.isOut).toList(growable: false),
        participantsInvitations =
            invitations.where((e) => e.memberRole.isParticipant).toList(growable: false),
        jurorsInvitations = invitations.where((e) => e.memberRole.isJuror).toList(growable: false),
        endedVotingSessions =
            votingSessions.where((e) => e.sessionStatus.isEnded).toList(growable: false),
        liveVotingSession = votingSessions
            .where((e) =>
                e.sessionStatus != VotingSessionStatus.ended &&
                e.sessionStatus != VotingSessionStatus.cancelled)
            .toList(growable: false)
            .firstOrNull;

  factory ContestDetailsBundle.fromRpcJson(Map<String, dynamic> json) {
    final participations = (json['participations'] as List<dynamic>)
        .map((e) => Participation.fromJson(e))
        .toList(growable: false);
    final participants = (json['participants'] as List<dynamic>)
        .map((e) => Profile.fromJson(e))
        .toList(growable: false);
    final works =
        (json['works'] as List<dynamic>).map((e) => Work.fromJson(e)).toList(growable: false);
    final jurations = (json['jurations'] as List<dynamic>)
        .map((e) => Juration.fromJson(e))
        .toList(growable: false);
    final jurors =
        (json['jurors'] as List<dynamic>).map((e) => Profile.fromJson(e)).toList(growable: false);
    final votingForm = VotingForm.fromJson(json['voting_form']);
    final votingFormFields = (json['voting_form_fields'] as List<dynamic>)
        .map((e) => VotingFormField.fromJson(e))
        .toList(growable: false);
    // votingFormFields.sort((a, b) => a.orderIndex.compareTo(b.orderIndex));

    final participationsBundles = participations.map((participation) {
      final participant =
          participants.firstWhere((participant) => participant.id == participation.participantId);
      final work = works.where((work) => work.participationId == participation.id).firstOrNull;
      return ParticipationBundle(
          participation: participation, participant: participant, work: work);
    }).toList(growable: false);

    final jurationsBundles = jurations.map((juration) {
      final juror = jurors.firstWhere((juror) => juror.id == juration.jurorId);
      return JurationBundle(juration: juration, juror: juror);
    }).toList(growable: false);

    final votingFormBundle =
        VotingFormBundle(votingForm: votingForm, votingFormFields: votingFormFields);

    return ContestDetailsBundle(
      contest: Contest.fromJson(json['contest']),
      organizer: Organizer.fromJson(json['organizer']),
      place: Place.fromJson(json['place']),
      invitations: (json['invitations'] as List<dynamic>)
          .map((e) => Invitation.fromJson(e))
          .toList(growable: false),
      votingSessions: (json['voting_sessions'] as List<dynamic>)
          .map((e) => VotingSession.fromJson(e))
          .toList(growable: false),
      participationsBundles: participationsBundles,
      jurationsBundles: jurationsBundles,
      votingFormBundle: votingFormBundle,
    );
  }

  factory ContestDetailsBundle.fromJson(Map<String, dynamic> json) {
    return ContestDetailsBundle(
      contest: Contest.fromJson(json['contest']),
      organizer: Organizer.fromJson(json['organizer']),
      place: Place.fromJson(json['place']),
      participationsBundles: (json['participations_bundles'] as List<dynamic>)
          .map((
            e,
          ) =>
              ParticipationBundle.fromJson(e))
          .toList(growable: false),
      jurationsBundles: (json['jurations_bundles'] as List<dynamic>)
          .map((
            e,
          ) =>
          JurationBundle.fromJson(e))
          .toList(growable: false),
      invitations: (json['invitations'] as List<dynamic>)
          .map((e) => Invitation.fromJson(e))
          .toList(growable: false),
      votingFormBundle: VotingFormBundle.fromJson(json['voting_form_bundle']),
      votingSessions: (json['voting_sessions'] as List<dynamic>)
          .map((e) => VotingSession.fromJson(e))
          .toList(growable: false),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'contest': contest.toJson(),
      'organizer': organizer.toJson(),
      'place': place.toJson(),
      'participations_bundles':
          participationsBundles.map((e) => e.toJson()).toList(growable: false),
      'jurations_bundles': jurationsBundles.map((e) => e.toJson()).toList(growable: false),
      'invitations': invitations.map((e) => e.toJson()).toList(growable: false),
      'voting_form_bundle': votingFormBundle.toJson(),
      'voting_sessions': votingSessions.map((e) => e.toJson()).toList(growable: false),
    };
  }

  ContestDetailsBundle copyWith({
    Contest? contest,
    Organizer? organizer,
    Place? place,
    List<ParticipationBundle>? participationsBundles,
    List<JurationBundle>? jurationsBundles,
    List<Invitation>? invitations,
    VotingFormBundle? votingFormBundle,
    List<VotingSession>? votingSessions,
  }) {
    return ContestDetailsBundle(
      contest: contest ?? this.contest,
      organizer: organizer ?? this.organizer,
      place: place ?? this.place,
      participationsBundles: participationsBundles ?? this.participationsBundles,
      jurationsBundles: jurationsBundles ?? this.jurationsBundles,
      invitations: invitations ?? this.invitations,
      votingFormBundle: votingFormBundle ?? this.votingFormBundle,
      votingSessions: votingSessions ?? this.votingSessions,
    );
  }

  @override
  List<Object?> get props => [
        contest,
        organizer,
        place,
        participationsBundles,
        jurationsBundles,
        invitations,
        votingFormBundle
      ];
}
