import 'package:equatable/equatable.dart';
import 'package:swift_contest/model/data_models/contest.dart';
import 'package:swift_contest/model/data_models/juration.dart';
import 'package:swift_contest/model/data_models/participation.dart';
import 'package:swift_contest/model/data_models/place.dart';
import 'package:swift_contest/model/data_models/profile.dart';
import 'package:swift_contest/model/enums/juror_status.dart';
import 'package:swift_contest/model/enums/participant_status.dart';

class HomeContestBundle extends Equatable {
  final Contest contest;
  final Organizer organizer;
  final Place place;
  final List<Participation> participations;
  final List<Juration> jurations;

  // Autogenerated
  final List<Participation> joinedParticipations;
  final List<Juration> joinedJurations;

  HomeContestBundle({
    required this.contest,
    required this.organizer,
    required this.place,
    required this.participations,
    required this.jurations,
  })  : joinedParticipations =
            participations.where((e) => e.participantStatus.isJoined).toList(growable: false),
        joinedJurations = jurations.where((e) => e.jurorStatus.isJoined).toList(growable: false);

  factory HomeContestBundle.fromJson(Map<String, dynamic> json) {
    return HomeContestBundle(
      contest: Contest.fromJson(json['contest']),
      organizer: Organizer.fromJson(json['organizer']),
      place: Place.fromJson(json['place']),
      participations: (json['participations'] as List<dynamic>)
          .map((e) => Participation.fromJson(e))
          .toList(growable: false),
      jurations: (json['jurations'] as List<dynamic>)
          .map((e) => Juration.fromJson(e))
          .toList(growable: false),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'contest': contest.toJson(),
      'organizer': organizer.toJson(),
      'place': place.toJson(),
      'participations': participations.map((e) => e.toJson()).toList(growable: false),
      'jurations': jurations.map((e) => e.toJson()).toList(growable: false),
    };
  }

  HomeContestBundle copyWith({
    Contest? contest,
    Organizer? organizer,
    Place? place,
    List<Participation>? participations,
    List<Juration>? jurations,
  }) {
    return HomeContestBundle(
      contest: contest ?? this.contest,
      organizer: organizer ?? this.organizer,
      place: place ?? this.place,
      participations: participations ?? this.participations,
      jurations: jurations ?? this.jurations,
    );
  }

  @override
  List<Object?> get props => [contest, organizer, place, participations, jurations];
}
