import 'package:equatable/equatable.dart';
import 'package:swift_contest/model/bundles/juration_bundle.dart';
import 'package:swift_contest/model/bundles/voting_form_bundle.dart';
import 'package:swift_contest/model/bundles/voting_session_juration_bundle.dart';
import 'package:swift_contest/model/bundles/voting_session_participation_bundle.dart';
import 'package:swift_contest/model/data_models/juration.dart';
import 'package:swift_contest/model/data_models/participation.dart';
import 'package:swift_contest/model/data_models/profile.dart';
import 'package:swift_contest/model/data_models/voting_form.dart';
import 'package:swift_contest/model/data_models/voting_session.dart';
import 'package:swift_contest/model/data_models/voting_session_exclusion.dart';
import 'package:swift_contest/model/data_models/voting_session_juration.dart';
import 'package:swift_contest/model/data_models/voting_session_participation.dart';
import 'package:swift_contest/model/data_models/work.dart';

import '../data_models/voting_form_field.dart';
import 'participation_bundle.dart';

class VotingSessionBundle extends Equatable {
  final VotingSession votingSession;
  final VotingFormBundle votingFormBundle;
  final List<VotingSessionParticipationBundle> votingSessionParticipationsBundles;
  final List<VotingSessionJurationBundle> votingSessionJurationsBundles;
  final List<VotingSessionExclusion> votingSessionExclusions;

  // Autogenerated
  final List<VotingSessionParticipationBundle> includedVotingSessionParticipationsBundles;
  final List<VotingSessionParticipationBundle> excludedVotingSessionParticipationsBundles;
  final List<VotingSessionJurationBundle> includedVotingSessionJurationsBundles;
  final List<VotingSessionJurationBundle> excludedVotingSessionJurationsBundles;

  VotingSessionBundle({
    required this.votingSession,
    required this.votingFormBundle,
    required this.votingSessionParticipationsBundles,
    required this.votingSessionJurationsBundles,
    required this.votingSessionExclusions,
  })  : includedVotingSessionParticipationsBundles = votingSessionParticipationsBundles
            .where((e) => !e.votingSessionParticipation.isExcluded)
            .toList(growable: false),
        includedVotingSessionJurationsBundles = votingSessionJurationsBundles
            .where((e) => !e.votingSessionJuration.isExcluded)
            .toList(growable: false),
        excludedVotingSessionParticipationsBundles = votingSessionParticipationsBundles
            .where((e) => e.votingSessionParticipation.isExcluded)
            .toList(growable: false),
        excludedVotingSessionJurationsBundles = votingSessionJurationsBundles
            .where((e) => e.votingSessionJuration.isExcluded)
            .toList(growable: false);

  factory VotingSessionBundle.fromRpcJson(Map<String, dynamic> json) {
    final List<Participation> participations = (json['participations'] as List<dynamic>)
        .map((e) => Participation.fromJson(e))
        .toList(growable: false);
    final List<Participant> participants = (json['participants'] as List<dynamic>)
        .map((e) => Participant.fromJson(e))
        .toList(growable: false);
    final List<Work> works =
        (json['works'] as List<dynamic>).map((e) => Work.fromJson(e)).toList(growable: false);
    final List<Juration> jurations = (json['jurations'] as List<dynamic>)
        .map((e) => Juration.fromJson(e))
        .toList(growable: false);
    final List<Juror> jurors =
        (json['jurors'] as List<dynamic>).map((e) => Juror.fromJson(e)).toList(growable: false);
    final VotingForm votingForm = VotingForm.fromJson(json['voting_form']);
    final List<VotingFormField> votingFormFields = (json['voting_form_fields'] as List<dynamic>)
        .map((e) => VotingFormField.fromJson(e))
        .toList(growable: false);
    votingFormFields.sort((a, b) => a.orderIndex.compareTo(b.orderIndex));
    final VotingSession votingSession = VotingSession.fromJson(json['voting_session']);
    final List<VotingSessionParticipation> votingSessionParticipations =
        (json['voting_session_participations'] as List<dynamic>)
            .map((e) => VotingSessionParticipation.fromJson(e))
            .toList(growable: false);
    final List<VotingSessionJuration> votingSessionJurations =
        (json['voting_session_jurations'] as List<dynamic>)
            .map((e) => VotingSessionJuration.fromJson(e))
            .toList(growable: false);
    final List<VotingSessionExclusion> votingSessionExclusions =
        (json['voting_session_exclusions'] as List<dynamic>)
            .map((e) => VotingSessionExclusion.fromJson(e))
            .toList(growable: false);

    final participationsBundles = participations.map((participation) {
      final participant =
          participants.firstWhere((participant) => participant.id == participation.participantId);
      final work = works.where((work) => work.participationId == participation.id).firstOrNull;
      return ParticipationBundle(
          participation: participation, participant: participant, work: work);
    }).toList(growable: false);

    final jurationsBundles = jurations.map((juration) {
      final juror = jurors.firstWhere((juror) => juror.id == juration.jurorId);
      return JurationBundle(juration: juration, juror: juror);
    }).toList(growable: false);

    final votingFormBundle =
        VotingFormBundle(votingForm: votingForm, votingFormFields: votingFormFields);

    final List<VotingSessionParticipationBundle> votingSessionParticipationsBundles =
        votingSessionParticipations.map((votingSessionParticipation) {
      final participationBundle = participationsBundles
          .firstWhere((e) => e.participation.id == votingSessionParticipation.participationId);
      return VotingSessionParticipationBundle(
        votingSessionParticipation: votingSessionParticipation,
        participationBundle: participationBundle,
      );
    }).toList(growable: false);

    final List<VotingSessionJurationBundle> votingSessionJurationsBundles =
    votingSessionJurations.map((votingSessionJuration) {
      final jurationBundle = jurationsBundles
          .firstWhere((e) => e.juration.id == votingSessionJuration.jurationId);
      return VotingSessionJurationBundle(
        votingSessionJuration: votingSessionJuration,
        jurationBundle: jurationBundle,
      );
    }).toList(growable: false);

    return VotingSessionBundle(
      votingSession: votingSession,
      votingFormBundle: votingFormBundle,
      votingSessionParticipationsBundles:
          votingSessionParticipationsBundles,
      votingSessionJurationsBundles: votingSessionJurationsBundles,
      votingSessionExclusions: votingSessionExclusions,
    );
  }

  factory VotingSessionBundle.fromJson(Map<String, dynamic> json) {
    return VotingSessionBundle(
      votingSession: VotingSession.fromJson(json['voting_session']),
      votingFormBundle: VotingFormBundle.fromJson(json['voting_form_bundle']),
      votingSessionParticipationsBundles:
          (json['voting_session_participations_bundles'] as List<dynamic>)
              .map((e) => VotingSessionParticipationBundle.fromJson(e))
              .toList(growable: false),
      votingSessionJurationsBundles: (json['voting_session_jurations_bundles'] as List<dynamic>)
          .map((e) => VotingSessionJurationBundle.fromJson(e))
          .toList(growable: false),
      votingSessionExclusions: (json['voting_session_exclusions'] as List<dynamic>)
          .map((e) => VotingSessionExclusion.fromJson(e))
          .toList(growable: false),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'voting_session': votingSession.toJson(),
      'voting_form_bundle': votingFormBundle.toJson(),
      'voting_session_participations_bundles':
          votingSessionParticipationsBundles.map((e) => e.toJson()).toList(),
      'voting_session_jurations_bundles':
          votingSessionJurationsBundles.map((e) => e.toJson()).toList(),
      'voting_session_exclusions': votingSessionExclusions.map((e) => e.toJson()).toList(),
    };
  }

  VotingSessionBundle copyWith({
    VotingSession? votingSession,
    VotingFormBundle? votingFormBundle,
    List<VotingSessionParticipationBundle>? votingSessionParticipationsBundles,
    List<VotingSessionJurationBundle>? votingSessionJurationsBundles,
    List<VotingSessionExclusion>? votingSessionExclusions,
  }) {
    return VotingSessionBundle(
      votingSession: votingSession ?? this.votingSession,
      votingFormBundle: votingFormBundle ?? this.votingFormBundle,
      votingSessionParticipationsBundles:
          votingSessionParticipationsBundles ?? this.votingSessionParticipationsBundles,
      votingSessionJurationsBundles:
          votingSessionJurationsBundles ?? this.votingSessionJurationsBundles,
      votingSessionExclusions: votingSessionExclusions ?? this.votingSessionExclusions,
    );
  }

  @override
  List<Object?> get props => [
        votingSession,
        votingFormBundle,
        votingSessionParticipationsBundles,
        votingSessionJurationsBundles,
        votingSessionExclusions,
      ];
}
