---- CREATE VOTING SESSION PROCEDURE
--CREATE OR REPLACE FUNCTION create_voting_session_procedure (
--  p_voting_session_procedure voting_session_procedures
--)
--RETURNS voting_session_procedures AS $$
--DECLARE
--  v_voting_session_procedure voting_session_procedures;
--BEGIN
--  INSERT INTO voting_session_procedures (
--    id,
--    created_at,
--    voting_session_id,
--    current_step,
--    current_participant_index,
--    current_step_deadline
--  )
--  VALUES (
--    p_voting_session_procedure.id,
--    p_voting_session_procedure.created_at,
--    p_voting_session_procedure.voting_session_id,
--    p_voting_session_procedure.current_step,
--    p_voting_session_procedure.current_participant_index,
--    p_voting_session_procedure.current_step_deadline
--  )
--  RETURNING * INTO STRICT v_voting_session_procedure;
--
--  RETURN v_voting_session_procedure;
--
--EXCEPTION
--  WHEN SQLSTATE 'P0001' THEN
--    RAISE;
--  WHEN OTHERS THEN
--    RAISE EXCEPTION 'An error occurred while creating the voting session procedure';
--END;
--$$ LANGUAGE plpgsql SECURITY DEFINER;
--
---- UPDATE VOTING SESSION PROCEDURE
--CREATE OR REPLACE FUNCTION update_voting_session_procedure (
--  p_voting_session_procedure voting_session_procedures
--)
--RETURNS voting_session_procedures AS $$
--DECLARE
--  v_voting_session_procedure voting_session_procedures;
--BEGIN
--  -- Verify if the voting session procedure exists
--  IF NOT EXISTS (SELECT 1 FROM voting_session_procedures WHERE id = p_voting_session_procedure.id) THEN
--    RAISE EXCEPTION 'No voting session procedure found';
--  END IF;
--
--  UPDATE voting_session_procedures
--  SET
--    voting_session_id = p_voting_session_procedure.voting_session_id,
--    current_step = p_voting_session_procedure.current_step,
--    current_participant_index = p_voting_session_procedure.current_participant_index,
--    current_step_voting_session_procedure.deadline = p_voting_session_procedure.current_step_deadline
--  WHERE id = p_voting_session_procedure.id
--  RETURNING * INTO STRICT v_voting_session_procedure;
--
--  RETURN v_voting_session_procedure;
--
--EXCEPTION
--  WHEN SQLSTATE 'P0001' THEN
--    RAISE;
--  WHEN OTHERS THEN
--    RAISE EXCEPTION 'An error occurred while updating the voting session procedure';
--END;
--$$ LANGUAGE plpgsql SECURITY DEFINER;
--
---- DELETE VOTING SESSION PROCEDURE BY ID
--CREATE OR REPLACE FUNCTION delete_voting_session_procedure_by_id(
--  p_id uuid
--)
--RETURNS voting_session_procedures AS $$
--DECLARE
--  v_voting_session_procedure voting_session_procedures;
--BEGIN
--  -- Verify if the voting session procedure exists
--  IF NOT EXISTS (SELECT 1 FROM voting_session_procedures WHERE id = p_id) THEN
--    RAISE EXCEPTION 'No voting session procedure found';
--  END IF;
--
--  DELETE FROM voting_session_procedures
--  WHERE id = p_id
--  RETURNING * INTO STRICT v_voting_session_procedure;
--
--  RETURN v_voting_session_procedure;
--
--EXCEPTION
--  WHEN SQLSTATE 'P0001' THEN
--    RAISE;
--  WHEN OTHERS THEN
--    RAISE EXCEPTION 'An error occurred while deleting the voting session procedure';
--END;
--$$ LANGUAGE plpgsql SECURITY DEFINER;
--
---- GET VOTING SESSION PROCEDURE BY ID
--CREATE OR REPLACE FUNCTION get_voting_session_procedure_by_id(
--  p_id uuid
--)
--RETURNS SETOF voting_session_procedures AS $$
--BEGIN
--  RETURN QUERY
--    SELECT *
--    FROM voting_session_procedures
--    WHERE id = p_id;
--
--EXCEPTION
--  WHEN SQLSTATE 'P0001' THEN
--    RAISE;
--  WHEN OTHERS THEN
--    RAISE EXCEPTION 'An error occurred while getting the voting session procedure';
--END;
--$$ LANGUAGE plpgsql SECURITY DEFINER;
--
---- GET VOTING SESSION PROCEDURE BY VOTING SESSION ID
--CREATE OR REPLACE FUNCTION get_voting_session_procedure_by_voting_session_id(
--  p_voting_session_id uuid
--)
--RETURNS SETOF voting_session_procedures AS $$
--BEGIN
--  RETURN QUERY
--    SELECT *
--    FROM voting_session_procedures
--    WHERE voting_session_id = p_voting_session_id;
--
--EXCEPTION
--  WHEN SQLSTATE 'P0001' THEN
--    RAISE;
--  WHEN OTHERS THEN
--    RAISE EXCEPTION 'An error occurred while getting the voting session procedure';
--END;
--$$ LANGUAGE plpgsql SECURITY DEFINER;
