@startuml

entity "profiles" {
    #id : uuid
    *created_at : timestamptz <<default:now()>>
    *full_name : varchar(70)
    *pref_role : contest_role <<default:'organizer'>>
}

entity "messages" {
    #id : uuid <<default:extensions.uuid_generate_v4()>>
    *created_at : timestamptz <<default:now()>>
    *account_id : uuid
    *title : varchar(50)
    *body : varchar(1000)
    *is_read : bool <<default:false>>
}

entity "places" {
    #id : uuid <<default:extensions.uuid_generate_v4()>>
    *created_at : timestamptz <<default:now()>>
    *address : varchar(255)
    *lat : float
    *lon : float
}

entity "voting_forms" {
    #id : uuid <<default:extensions.uuid_generate_v4()>>
    *created_at : timestamptz <<default:now()>>
    *name : varchar(50)
    *description : varchar(1000)
}

entity "voting_form_fields" {
    #id : uuid <<default:extensions.uuid_generate_v4()>>
    *created_at : timestamptz <<default:now()>>
    *voting_form_id : uuid
    *question : varchar(255)
    *order_index : int
    *type : voting_form_field_type
    slider_min_value : int
    slider_max_value : int
    *is_required : bool
    *scope : voting_form_field_scope
}

entity "contests" {
    #id : uuid <<default:extensions.uuid_generate_v4()>>
    *created_at : timestamptz <<default:now()>>
    *organizer_id : uuid
    *name : varchar(50)
    *description : varchar(1000)
    *date_time : timestamptz
    *works_submission_start : timestamptz
    *works_submission_end : timestamptz
    *place_id : uuid
    *images_paths : text[]
}

entity "participant_invitations" {
    #id : uuid <<default:extensions.uuid_generate_v4()>>
    *created_at : timestamptz <<default:now()>>
    *contest_id : uuid
    *token : varchar(14) <<default:public.gen_unique_token('participant_invitations', 'token', 14)>>
    *email : varchar(254)
}

entity "juries" {
    #id : uuid <<default:extensions.uuid_generate_v4()>>
    *created_at : timestamptz <<default:now()>>
    *contest_id : uuid
    *voting_form_id : uuid
    *token : varchar(14) <<default:public.gen_unique_token('juries', 'token', 14)>>
    *name : varchar(50)
    *type : jury_type
}

entity "juror_invitations" {
    #id : uuid <<default:extensions.uuid_generate_v4()>>
    *created_at : timestamptz <<default:now()>>
    *contest_id : uuid
    *jury_id : uuid
    *token : varchar(14) <<default:public.gen_unique_token('juror_invitations', 'token', 14)>>
    *email : varchar(254)
}

entity "participations" {
    #id : uuid <<default:extensions.uuid_generate_v4()>>
    *created_at : timestamptz <<default:now()>>
    *contest_id : uuid
    *participant_id : uuid
    *invitation_email : varchar(254)
    *has_submitted : bool <<default:false>>
}

entity "works" {
    #id : uuid <<default:extensions.uuid_generate_v4()>>
    *created_at : timestamptz <<default:now()>>
    *participation_id : uuid
    *name : varchar(50)
    *description : varchar(1000)
    *images_paths : text[]
    *file_path : text
}

entity "jurations" {
    #id : uuid <<default:extensions.uuid_generate_v4()>>
    *created_at : timestamptz <<default:now()>>
    *contest_id : uuid
    *jury_id : uuid
    *juror_id : uuid
    *invitation_email : varchar(254)
}

entity "voting_sessions" {
    #id : uuid <<default:extensions.uuid_generate_v4()>>
    *created_at : timestamptz <<default:now()>>
    *name : varchar(50)
    *contest_id : uuid
    *is_geo_restricted : bool
    geo_res_place_id : uuid
    geo_res_radius : int
    *session_status : voting_session_status
}

entity "voting_session_participants" {
    #id : uuid <<default:extensions.uuid_generate_v4()>>
    *created_at : timestamptz <<default:now()>>
    *voting_session_id : uuid
    participation_id : uuid
    *order_index : int
    *participant_full_name : varchar(70)
    *work_name : varchar(50)
    *work_description : varchar(1000)
    *work_images_paths : text[]
}

entity "voting_session_juries" {
    #id : uuid <<default:extensions.uuid_generate_v4()>>
    *created_at : timestamptz <<default:now()>>
    *voting_session_id : uuid
    jury_id : uuid
    *jury_name : varchar(50)
    *jury_type : jury_type
    *voting_form_id : uuid
    *jury_token : varchar(14)
}

entity "voting_session_jurors" {
    #id : uuid <<default:extensions.uuid_generate_v4()>>
    *created_at : timestamptz <<default:now()>>
    *voting_session_id : uuid
    *voting_session_jury_id : uuid
    juration_id : uuid
    juror_id : uuid
    *has_submitted : bool <<default:false>>
    *juror_full_name : varchar(70)
}

entity "voting_session_exclusions" {
    #id : uuid <<default:extensions.uuid_generate_v4()>>
    *created_at : timestamptz <<default:now()>>
    *voting_session_id : uuid
    *voting_session_juror_id : uuid
    *voting_session_participant_id : uuid
}

entity "voting_form_submissions" {
    #id : uuid <<default:extensions.uuid_generate_v4()>>
    *created_at : timestamptz <<default:now()>>
    *voting_session_id : uuid
    voting_session_juror_id : uuid
}

entity "voting_form_submission_values" {
    #id : uuid <<default:extensions.uuid_generate_v4()>>
    *voting_form_submission_id : uuid
    *voting_form_field_id : uuid
    *value : text
    voting_session_participant_id : uuid
}

entity "contest_rankings" {
    #id : uuid <<default:gen_random_uuid()>>
    *created_at : timestamptz <<default:now()>>
    *contest_id : uuid
    *file_path : text
}

@enduml
